name: data_literacy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - conda=23.11.0
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - pip

  - pip:
    - statsmodels
    - openpyxl
    - nbconvert
    - seaborn
    - tueplots
    - networkx
    - reportlab
