name: Run Python script and create PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: data_literacy
        environment-file: data_literacy.yml
        auto-activate-base: false

    - name: Run Python script
      run: python runAll.py
      shell: bash -l {0}

    - name: Compile LaTeX documents
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          doc/DataLiteracyStudentProject/paper.tex

    - name: Upload PDFs
      uses: actions/upload-artifact@v2
      with:
        name: PDFs
        path: ./*.pdf