name: Test GitHub Token

on: [push]

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GITHUB_TOKEN
        run: |
            echo "GITHUB_TOKEN: ${{ secrets.GitHubActionsToken }}"
        env:
          GH_TOKEN: ${{ secrets.GitHubActionsToken }}
    